"""
Architecture violation tests for vvuq-technical-validator plugin.
Generated by Architecture Critic - 2026-02-22

NOTE: This is a markdown-based plugin. Architecture tests verify
structure and organization, not SOLID principles (no classes exist).
"""
import pytest
import json
from pathlib import Path


PLUGIN_ROOT = Path(__file__).parent.parent.parent


class TestPluginStructure:
    """Verify plugin has correct directory structure."""

    def test_skill_file_exists(self):
        """
        CLAUDE.md Rule: "Skills require SKILL.md"
        Found: skills/vvuq-validator/SKILL.md
        """
        skill_file = PLUGIN_ROOT / "skills" / "vvuq-validator" / "SKILL.md"
        assert skill_file.exists(), f"SKILL.md must exist at {skill_file}"

    def test_commands_directory_exists(self):
        """
        CLAUDE.md Rule: "Commands defined in commands/"
        Verification: Commands directory with .md files
        """
        commands_dir = PLUGIN_ROOT / "commands"
        assert commands_dir.exists(), "commands/ directory must exist"

        md_files = list(commands_dir.glob("*.md"))
        assert len(md_files) >= 1, "At least one command must exist"

    def test_plugin_manifest_exists(self):
        """Plugin manifest at .claude-plugin/plugin.json"""
        manifest = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        assert manifest.exists(), "plugin.json must exist"


class TestCommandConsistency:
    """Verify commands follow consistent patterns."""

    def test_all_commands_have_frontmatter(self):
        """
        CLAUDE.md Rule: "Command Development - YAML frontmatter"
        """
        commands_dir = PLUGIN_ROOT / "commands"
        if not commands_dir.exists():
            pytest.skip("No commands directory")

        for cmd_file in commands_dir.glob("*.md"):
            content = cmd_file.read_text()
            assert content.startswith("---"), \
                f"{cmd_file.name} must start with YAML frontmatter"
            assert content.count("---") >= 2, \
                f"{cmd_file.name} must have closing frontmatter delimiter"

    def test_commands_have_description(self):
        """Commands must have description in frontmatter."""
        commands_dir = PLUGIN_ROOT / "commands"
        if not commands_dir.exists():
            pytest.skip("No commands directory")

        for cmd_file in commands_dir.glob("*.md"):
            content = cmd_file.read_text()
            assert "description:" in content, \
                f"{cmd_file.name} must have description"


class TestBenchmarkOrganization:
    """Verify benchmark data is well-organized."""

    def test_benchmark_has_test_cases_dir(self):
        """Benchmark test cases in dedicated directory."""
        test_cases = PLUGIN_ROOT / "benchmarks" / "test_cases"
        assert test_cases.exists(), "benchmarks/test_cases/ must exist"

    def test_benchmark_has_results_dir(self):
        """Benchmark results in dedicated directory."""
        results = PLUGIN_ROOT / "benchmarks" / "results"
        assert results.exists(), "benchmarks/results/ must exist"


def test_architecture_review_completed():
    """
    Architecture Review: vvuq-technical-validator plugin

    Structure: Markdown-based Claude Code plugin
    - skills/: SKILL.md definition
    - commands/: Slash command definitions
    - benchmarks/: Test cases and results
    - .claude-plugin/: Plugin manifest

    This is a prompt-engineering plugin, not a code library.
    SOLID principles don't apply (no classes/interfaces).

    Status: Architecture tests PASS
    """
    assert True
