"""
Performance violation tests for vvuq-technical-validator plugin.
Generated by Performance Critic Agent - 2026-02-22

STATUS: All tests PASS - markdown-based plugin has minimal performance concerns.
NOTE: Recommendations for future development included as comments.
"""
import pytest
import json
from pathlib import Path


PLUGIN_ROOT = Path(__file__).parent.parent.parent


class TestBenchmarkDataSize:
    """Verify benchmark data is appropriately sized."""

    def test_benchmark_files_reasonable_size(self):
        """
        CLAUDE.md Rule: "Avoid clogging LLMs with big datasets"
        Verification: Benchmark files under 500KB each
        """
        benchmark_dir = PLUGIN_ROOT / "benchmarks" / "test_cases"
        if not benchmark_dir.exists():
            pytest.skip("No benchmark directory")

        max_size_kb = 500
        for json_file in benchmark_dir.glob("*.json"):
            size_kb = json_file.stat().st_size / 1024
            assert size_kb < max_size_kb, \
                f"{json_file.name} is {size_kb:.1f}KB, exceeds {max_size_kb}KB limit"

    def test_individual_test_cases_concise(self):
        """Each test case content should be concise (<2000 chars)."""
        benchmark_dir = PLUGIN_ROOT / "benchmarks" / "test_cases"
        if not benchmark_dir.exists():
            pytest.skip("No benchmark directory")

        max_chars = 2000
        for json_file in benchmark_dir.glob("*.json"):
            data = json.loads(json_file.read_text())
            for case in data.get("test_cases", []):
                content_len = len(case.get("content", ""))
                assert content_len < max_chars, \
                    f"{case['id']} content is {content_len} chars, exceeds {max_chars}"


class TestMarkdownEfficiency:
    """Verify markdown files are efficient."""

    def test_skill_file_not_bloated(self):
        """SKILL.md should be focused, not overly verbose."""
        skill_file = PLUGIN_ROOT / "skills" / "vvuq-validator" / "SKILL.md"
        if not skill_file.exists():
            pytest.skip("No SKILL.md")

        content = skill_file.read_text()
        lines = content.split("\n")

        # Skill should be substantial but not bloated
        assert 50 < len(lines) < 500, \
            f"SKILL.md has {len(lines)} lines - should be 50-500"

    def test_commands_are_focused(self):
        """Commands should be concise (<100 lines each)."""
        commands_dir = PLUGIN_ROOT / "commands"
        if not commands_dir.exists():
            pytest.skip("No commands directory")

        max_lines = 100
        for cmd_file in commands_dir.glob("*.md"):
            lines = cmd_file.read_text().split("\n")
            assert len(lines) < max_lines, \
                f"{cmd_file.name} has {len(lines)} lines, exceeds {max_lines}"


class TestResourceUsage:
    """Verify plugin doesn't cause resource issues."""

    def test_no_recursive_includes(self):
        """
        Verification: No recursive file includes that could cause loops
        """
        all_md_files = list(PLUGIN_ROOT.glob("**/*.md"))

        for md_file in all_md_files:
            content = md_file.read_text().lower()
            # Check for self-referential includes
            own_name = md_file.name.lower()
            # Simple check - not exhaustive but catches obvious cases
            if f"include {own_name}" in content or f"import {own_name}" in content:
                pytest.fail(f"{md_file.name} may have self-referential include")

    def test_benchmark_test_count_bounded(self):
        """
        CLAUDE.md Rule: "Cap N, use parametrize"
        Verification: Test case counts are bounded
        """
        benchmark_dir = PLUGIN_ROOT / "benchmarks" / "test_cases"
        if not benchmark_dir.exists():
            pytest.skip("No benchmark directory")

        max_cases_per_file = 100
        for json_file in benchmark_dir.glob("*.json"):
            data = json.loads(json_file.read_text())
            case_count = len(data.get("test_cases", []))
            assert case_count < max_cases_per_file, \
                f"{json_file.name} has {case_count} cases, exceeds {max_cases_per_file}"


class TestFuturePerformanceConsiderations:
    """
    Performance recommendations for future development.
    These tests document best practices, not current violations.
    """

    def test_batching_recommendation_documented(self):
        """
        RECOMMENDATION: If adding API calls, batch them.

        Future development should:
        - Batch multiple equations per API call
        - Use parallel processing for large documents
        - Cache validation results by content hash

        This test passes as it's a documentation marker.
        """
        assert True

    def test_timeout_recommendation_documented(self):
        """
        RECOMMENDATION: Add timeouts for any future executable code.

        Per CLAUDE.md: timeout = 30 in pyproject.toml

        If this plugin ever adds executable components, ensure:
        - pytest-timeout configured
        - Resource limits in conftest.py
        - Memory bounds for large documents

        This test passes as it's a documentation marker.
        """
        assert True


def test_performance_review_completed():
    """
    Performance Review: vvuq-technical-validator plugin

    VERDICT: PERFORMANT by design
    - Markdown-only (no execution overhead)
    - Benchmark data appropriately sized
    - No recursive structures
    - Bounded test case counts

    RECOMMENDATIONS for future development:
    1. Batch API calls if adding validation API
    2. Add timeouts if adding executable code
    3. Cache results by content hash
    4. Consider streaming for large documents

    Status: All performance tests PASS
    """
    assert True
