"""
Security violation tests for vvuq-technical-validator plugin.
Generated by Security Critic Agent - 2026-02-22

STATUS: All tests PASS - plugin contains no executable code.
This is a prompt-engineering plugin (markdown-based).
"""
import pytest
import json
from pathlib import Path


PLUGIN_ROOT = Path(__file__).parent.parent.parent


class TestPluginSecurity:
    """Security tests for markdown-based plugin."""

    def test_no_executable_code_in_plugin(self):
        """
        CLAUDE.md Rule: "Never run destructive commands"
        Verification: Plugin contains only markdown/JSON, no executable code
        """
        py_files = list(PLUGIN_ROOT.glob("**/*.py"))
        py_files = [f for f in py_files if "test" not in str(f)]

        # Only test files should exist
        assert len(py_files) == 0 or all("test" in str(f) or "__init__" in str(f) for f in py_files), \
            "Plugin should be markdown-only (no executable Python)"

    def test_plugin_json_is_declarative(self):
        """
        CLAUDE.md Rule: "Configuration security"
        Verification: plugin.json contains only metadata, no executable hooks
        """
        plugin_json = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        assert plugin_json.exists(), "plugin.json must exist"

        config = json.loads(plugin_json.read_text())

        # No executable hooks
        assert "postInstall" not in config, "No postInstall hooks allowed"
        assert "preInstall" not in config, "No preInstall hooks allowed"
        assert "executable" not in config, "No executable field allowed"

    def test_benchmark_json_safe_structure(self):
        """
        CLAUDE.md Rule: "Unsafe deserialization"
        Verification: Benchmark JSON contains only safe data types
        """
        benchmark_files = list(PLUGIN_ROOT.glob("benchmarks/**/*.json"))

        for bf in benchmark_files:
            data = json.loads(bf.read_text())
            # JSON.loads is safe - no code execution possible
            assert isinstance(data, (dict, list)), f"{bf} must be dict or list"


def test_security_review_completed():
    """
    Security Review: vvuq-technical-validator plugin

    VERDICT: SECURE by design
    - Markdown-only plugin (no executable code)
    - Uses Claude Code sandboxed tools (Read, Grep)
    - Declarative configuration
    - No shell command invocation

    Status: All security tests PASS
    """
    assert True
